Repository retaildevcrews/relayrunner, pull requests merged in 2021-08, with the labels that each got.

#18 Linter config
  .github/workflows/relayrunner-pr.yml
  client/.eslintrc.json
  client/Dockerfile
  client/package.json
  client/src/components/Configs/index.js
  client/src/components/LoadClients/index.js
  client/src/components/LoadClients/sort.test.js
  client/src/data/configs.js
  client/src/data/loadClients.js
  client/src/data/loadTests.js
Labels: CI/CD

#19 Update documentation and fix npm warnings and vulnerabilities
  client/README.md
  client/package-lock.json
  client/package.json
Labels: Documentation, dependencies

#21 Starting Point for Data Definitions
  .devcontainer/devcontainer.json
  .vscode/settings.json
  docs/DataDictionary.md
  docs/diagrams/README.md
  docs/diagrams/out/ClientStatus Flow.svg
  docs/diagrams/source/StatusFlow.puml
Labels: DesignReview, Documentation

#24 Github Workflows for Merge
  .github/workflows/relayrunner-pr.yml
  .github/workflows/relayrunner.yml
Labels: CI/CD

#25 Setup CosmosDB for clientStatus (and loadClient)
  README.md
  backend/secrets/CosmosCollection
  backend/secrets/CosmosUrl
  docs/DataDictionary.md
  docs/cosmos.md
  scripts/cosmos-create.sh
Labels: Documentation, Enhancement
